### PR TITLE
Apply modifiers to only leaf classes (but including descendents)

### PR DESCRIPTION
**Pull request by jimsteel**

### CODE REVIEW

**Comment by jimsteel** [comment]
@jpwiedekopf Could you have a look at this one and see if it works for your CodeSystems?

**Comment by jpwiedekopf** [comment]
Hey, just a quick note to let you know that I am on holiday until tomorrow. I'll take a look on Monday, but I have taken a very quick look and have noted that there were a bunch of large-ish hunks that differed when converting ICD-10-GM with a) the previous commit with the initial modifier support and b) this PR. I'd have expected that there would be no changes between a and b.

What I'm going to do on Monday is verify that the list of codes is consistent with the metadata file that the DIMDI (authors of ICD-10-GM) provide. That's a CSV file listing all of the codes, including leaves. Perhaps we can find some pattern this way...

**Comment by jpwiedekopf** [comment]
Hi! I've now had the chance to take a look at the output for ICD-10-GM 2021, especially compared to the "official" (it's provided by DIMDI, but it's not to be considered authoritative) metadata files ([metadata download](https://www.dimdi.de/dynamic/.downloads/klassifikationen/icd-10-gm/version2021/icd10gm2021syst-meta-20201111.zip), [CLaML download](https://www.dimdi.de/dynamic/.downloads/klassifikationen/icd-10-gm/version2021/icd10gm2021syst-claml-20201111.zip)) 

First, it unfortunately looks like this PR (I'll call it the NL version) seems to remove the concepts that the previous fix ("DE") introduces, as the way the Dutch CLaML format uses modifiers seems to be very different to the GM version.

I've written a script to invoke the three versions ("nomod" for the previous commit without any modifiers, "de" and "nl" for the new versions) on the 2021 CLaML files. It then extracts all of the concepts with displays using [jq](https://stedolan.github.io/jq/) to NDJSON format, along with one file containing only the codes without displays. To compare with the metadata, it also extracts the respective data from the plain-text `*kodes.txt` file to NDJSON. The script and output files are at https://cloud.imi.uni-luebeck.de/s/xnTCmxp2Ej3Py6S (it exceed GitHub's size constraint of 10MB).

When comparing these output files with GNU diff (codes only, written to `./comparisons`) or a visual tool like Meld, the differences become obvious. First, consider the diff `nomod-metadata.diff`: a lot of codes are missing in the nomod version, as expected, since the modifiers are missing. Now, going from nomod to de, those codes are generally added by the "German" fix. If we compare de and nl, the same codes disappear - indeed, `nomod-nl.diff` is empty, *so every code added by modifiers in the DE version is not considered by the NL version.* This makes this PR fundamentally incompatible with the ICD-10-GM code system, and I would suspect that similar behaviour happens with OPS.

The good news is: if I compare `de-metadata.diff`, I can't find any codes missing in DE that should be there according to the metadata - meaning the modifiers for DE work wonderfully. The only things that differ are the categories (which might be an artefact of how I write those to the metadata file) and cross-star-codes, where the exclamation points and asterisks are missing in the FHIR-CLaML output (again, probably intended). 

Another thing from a diff of the de.ndjson file against metadata.ndjson (both with display strings), the displays for modifier codes seem to differ consistently: `{"code":"D23.0","display":"Sonstige gutartige Neubildungen: Lippenhaut"}` (metadata) vs `{"code":"D23.0","display":"Lippenhaut"}`, but that's another matter. This doesn't seem to happen consistently, some concepts like C88.00 have the prefix "Makroglobulinämie Waldenström" (but there is an errant space character in the FHIR-CLaML output). This probably has to do with the modifier being applied on the fifth place of the code, not on the fourth like for D23.-

In my opinion, this last point would be another grounds for improvement of FHIR-CLaML, independent of the issue we have with this PR.

**Comment by jimsteel** [comment]
Hi @jpwiedekopf,

If you get a chance, could you try this updated version with your scripts? There are still some issues (e.g. the +/*/! usages, and the D23 vs D23._ syntax difference), but I'm hoping it should be a bit better. I did some comparisons with the DIMDI metadata release (and a similar comparison with the NL code list), and I think it might be OK, but I'd welcome feedback.

Jim.

**Comment by jpwiedekopf** [comment]
Hi @jimsteel ,

it's looking good from my end! Using the script linked above, the "new" PR seems to provide an identical list of codes to the "de" version that has been merged into the upstream. This means that all the codes removed by the previous PR have been re-added with this new version of yours, and that no codes are missing for GM in general, as confimed previously.

Best,
Joshua

**Comment by jimsteel** [comment]
@lawley Do you want to have a look over the code?

**Review by dionmcm — APPROVED** [review]

**Pull request merged**
